
pipeline:
  test:
    image: docker.pkg.github.com/kaeedo/fablebuilder/fablebuild:latest
    commands:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - CI=true
      - pnpm i --unsafe-perm
      - pnpm run test
    when:
      event: tag
  publish:
    image: docker.pkg.github.com/kaeedo/fablebuilder/fablebuild:latest
    commands:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - CI=true
      - dotnet fsi "updateVersion.fsx"
    when:
      event: tag
services:
  etebase-server:
    image: etesync/test-server:latest
    when:
      event: tag