
pipeline:
  test:
    image: docker.pkg.github.com/kaeedo/fablebuilder/fablebuild:latest
    commands:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - CI=true
      - pnpm i --unsafe-perm
      - pnpm run test
    when:
      branch: main
  publish:
    image: docker.pkg.github.com/kaeedo/fablebuilder/fablebuild:latest
    commands:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - CI=true
      - dotnet fsi "updateVersion.fsx"
      - dotnet pack -c Release ./src/Fable.Etebase.fsproj
      - dotnet nuget push ./src/bin/Release/Fable.Etebase.*.nupkg -k $NUGET_PUSH -s https://api.nuget.org/v3/index.json
    when:
      event: tag
      branch: main
    secrets: [ nuget_push ]
services:
  etebase-server:
    image: etesync/test-server:latest
    when:
      branch: main
