pipeline:
  test:
    image: cl00e9ment/node.js-builder:light
    commands:
      - npm i -g pnpm
      - pnpm i
      - pnpm run test
  a-test-step:
    image: cl00e9ment/node.js-builder:light
    commands:
      - echo "Testing..."