pipeline:
  test:
    image: nojaf/fable:2.6
    commands:
      - npm i -g pnpm
      - pnpm i --unsafe-perm
      - mkdir ./dist
      - mkdir ./tests
      - pnpm run test
      - ls ../../
      - ls ./dist
      - ls ./dist/tests
  a-test-step:
    image: nojaf/fable:2.6
    commands:
      - echo "Testing..."